/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form.java;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author hadwa01
 */
public class FormerJPanel extends javax.swing.JPanel {

    ArrayList<Form> Former = new ArrayList<>();

    /**
     * Creates new form FormerJPanel
     */
    public FormerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCircel = new javax.swing.JButton();
        btnRektangel = new javax.swing.JButton();
        btnTriangel = new javax.swing.JButton();
        btnRensa = new javax.swing.JButton();

        btnCircel.setText("Circel");
        btnCircel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircelActionPerformed(evt);
            }
        });

        btnRektangel.setText("Rektangel");
        btnRektangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRektangelActionPerformed(evt);
            }
        });

        btnTriangel.setText("Triangel");
        btnTriangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangelActionPerformed(evt);
            }
        });

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnCircel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRektangel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTriangel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnRensa)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCircel)
                    .addComponent(btnRektangel)
                    .addComponent(btnTriangel)
                    .addComponent(btnRensa))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTriangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangelActionPerformed

        int x = (int) (Math.random() * 301);
        int y = (int) (Math.random() * 301);
        int b = (int) (Math.random() * 101);
        int h = (int) (Math.random() * 101);
        Form t = new Triangel(x, y, b, h, true);
        Former.add(t);
        repaint();

    }//GEN-LAST:event_btnTriangelActionPerformed

    private void btnCircelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircelActionPerformed

        int x = (int) (Math.random() * 301);
        int y = (int) (Math.random() * 301);
        int r = (int) (Math.random() * 50);
        Form c = new Circel(x, y, r, true);
        Former.add(c);
        repaint();
    }//GEN-LAST:event_btnCircelActionPerformed

    private void btnRektangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRektangelActionPerformed

        int x = (int) (Math.random() * 301);
        int y = (int) (Math.random() * 301);
        int b = (int) (Math.random() * 101);
        int h = (int) (Math.random() * 101);
        Form r = new Rektangel(x, y, b, h, true);
        Former.add(r);
        repaint();
    }//GEN-LAST:event_btnRektangelActionPerformed

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        this.Former.clear();
        repaint();
    }//GEN-LAST:event_btnRensaActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < Former.size(); i++) {
            Former.get(i).draw(g);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCircel;
    private javax.swing.JButton btnRektangel;
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnTriangel;
    // End of variables declaration//GEN-END:variables

}
