/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form.java;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author hadwa01
 */
public class FormerJPanel extends javax.swing.JPanel implements Runnable {

    private volatile Thread trad;

    ArrayList<Form> Former = new ArrayList<>();
    FileManager fmgr = new FileManager();
    private boolean running = false;

    /**
     * Creates new form FormerJPanel
     */
    public FormerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnRensa = new javax.swing.JButton();
        rbtnTriangel = new javax.swing.JRadioButton();
        rbtnRektangel = new javax.swing.JRadioButton();
        rbtnCircel = new javax.swing.JRadioButton();
        btnHämta = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        btnStartStop = new javax.swing.JToggleButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTriangel);
        rbtnTriangel.setText("Triangel");
        rbtnTriangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTriangelActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRektangel);
        rbtnRektangel.setText("Rektangel");
        rbtnRektangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRektangelActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnCircel);
        rbtnCircel.setSelected(true);
        rbtnCircel.setText("Circel");
        rbtnCircel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCircelActionPerformed(evt);
            }
        });

        btnHämta.setText("Hämta");
        btnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnStartStop.setText("Start");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbtnCircel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnRektangel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnTriangel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStartStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHämta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRensa)
                    .addComponent(btnSpara))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTriangel)
                    .addComponent(rbtnRektangel)
                    .addComponent(rbtnCircel)
                    .addComponent(btnHämta)
                    .addComponent(btnSpara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartStop)
                    .addComponent(btnRensa))
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        this.Former.clear();
        repaint();
    }//GEN-LAST:event_btnRensaActionPerformed

    private void rbtnTriangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTriangelActionPerformed

    }//GEN-LAST:event_rbtnTriangelActionPerformed

    private void rbtnRektangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRektangelActionPerformed

    }//GEN-LAST:event_rbtnRektangelActionPerformed

    private void rbtnCircelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCircelActionPerformed

    }//GEN-LAST:event_rbtnCircelActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        int b = (int) (Math.random() * 101);
        int h = (int) (Math.random() * 101);

        if (rbtnCircel.isSelected()) {
            Form c = new Circel(x - h / 2, y - h / 2, h, true);
            c.setRunning(running);
            Former.add(c);
        } else if (rbtnRektangel.isSelected()) {
            Form r = new Rektangel(x - b / 2, y - h / 2, b, h, true);
            r.setRunning(running);
            Former.add(r);
        } else if (rbtnTriangel.isSelected()) {
            Form t = new Triangel(x - b / 2, y + h / 2, b, h, true);
            t.setRunning(running);
            Former.add(t);
        }

        repaint();


    }//GEN-LAST:event_formMouseClicked

    private void btnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaActionPerformed
        Former = fmgr.readFromFile();
        repaint();
    }//GEN-LAST:event_btnHämtaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        fmgr.saveToFile(Former);

    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        if (this.btnStartStop.getText().equals("Start")) {
            this.btnStartStop.setText("Stop");
            start();
        } else {
            this.btnStartStop.setText("Start");
            stop();
        }
        for (int i = 0; i < Former.size(); i++) {

            Former.get(i).setRunning(running);
        }
        repaint();
    }//GEN-LAST:event_btnStartStopActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < Former.size(); i++) {

            Former.get(i).draw(g);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämta;
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnSpara;
    private javax.swing.JToggleButton btnStartStop;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbtnCircel;
    private javax.swing.JRadioButton rbtnRektangel;
    private javax.swing.JRadioButton rbtnTriangel;
    // End of variables declaration//GEN-END:variables

    private void start() {
        if (trad == null) {
            trad = new Thread(this);
            trad.start();
            this.running = true;
        }
    }

    private void stop() {
        if (trad != null) {
            this.running = false;
            trad = null;
        }
    }

    @Override
    public void run() {
        Thread thisThread = Thread.currentThread();
        while (trad == thisThread) {
            try {
                Thread.sleep(30);
            } catch (InterruptedException e) {
            }
            repaint();
        }
    }

}
